config/routes.rb
Rails.application.routes.draw do

  resources :house
  patch 'house/:id', to: 'house#buy'
  # get 'house/:id', to: 'house#show'
  root to: 'house#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3}
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/house_controller.rb
class HouseController < ApplicationController

    def index
        @house = House.all
    end

    def show
        @house = House.find_by id: params[:id]

    end

    def buy
        @house = House.find(params[:id])
        @house.update_attributes!(bye: true)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/views/house/index.html.erb
<br>
  <% @house.each do |house| %>
      <h2><%= link_to house.name, house_path(@house) %></h2>
  <% end %>

app/views/house/show.html.erb
<!--  <h2><%#= @house.name %></h2>-->
<!--  <p><%#  @house.price.each_index do |x| %>-->
      <%#= x+1  %>
      <%# end %>
<!--    <h2><%#= @house.inspect %></h2>-->

<!--  <%#= link_to "Buy", "/house/#{@house.id}",  class: "btn btn-success"  %> </p>-->
<!--  <h3>-->
    <%# @house.price.each_with_index do |el, index| %>
        <%# if  el[index].to_i <= el[index+1].to_i %>
            <%#= el[index+1] %>
        <%# else %>
            <%#= el[index] %>
        <%# end %>
    <%# end %>
<!--  </h3>-->

<h1><% @houses.each do |house| %>
    <%= house.name %>
    <% end %>
</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Trade Houses</title>
  </head>

  <body>
    <div class="container">
      <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>